// Complete list of NHKA Congregations (Gemeentes)
export const NHKA_GEMEENTES = [
  'Alberton',
  'Alberton-Wes',
  'ANDER',
  'Balfour',
  'Barberton',
  'Benoryn',
  'Bergsig',
  'Bethal',
  'Bethlehem',
  'Bloemfontein',
  'Bloemfontein-Wes',
  'Boksburg',
  'Bothaville',
  'Breyten',
  'Brits',
  'Bronkhorstspruit',
  'Buiteland',
  'Bybelgenootskap',
  'Calder',
  'Carletonville',
  'Centurion-Oos',
  'Chrissiesmeer',
  'Christiana',
  'Culembeeck',
  'Declercqville',
  'Delareyville',
  'Delmas',
  'Deo Volente',
  'Derde Kruis',
  'Derdepoort',
  'Dippenaar',
  'Drie Riviere',
  'Drie Riviere-Oos',
  'Duncanville',
  'Ebenhaeset',
  'Eendracht',
  'El-Flora',
  'Elandspoort',
  'Elsburg',
  'Emmaus Kenleaf',
  'Erasmia',
  'Ermelo',
  'Fourie',
  'Gaborone',
  'Gerdau',
  'Germiston',
  'Glencoe',
  'Gobabis',
  'Goudveld',
  'Greylingstad',
  'Grimbeekpark',
  'Groeneweide',
  'Groot Marico',
  'Grootfontein',
  'Harare',
  'Hartebeeshoek',
  'Hartebeestpoort',
  'Heidelberg',
  'Hoedspruit',
  'Horison Roodepoort',
  'Horn',
  'Jansen',
  'Jeffreysbaai',
  'Joachim Prinsloo',
  'Johannesburg',
  'Jordaan',
  'Kaapstad',
  'Kampersrus',
  'Kathu',
  'Kempten',
  'Kempton',
  'Kempton Park-Oos',
  'Klerksdorp-Doringkruin',
  'Klerksdorp-Oos',
  'Klerksdorp-Suid',
  'Klerksdorp-Wilkoppies',
  'Klerksdorp/emeritaat',
  'Komatipoort',
  'Koodoesrand',
  'Koster',
  'Kriel',
  'Krugersdorp-Noord',
  'Krugersdorp-Oos',
  'Krugersdorp-Wes',
  'Kruin',
  'Kruispad',
  'Laer Suidkus',
  'Laeveld',
  'Leeudoringstad',
  'Letsitele',
  'Lichtenburg',
  'Lichtenburg-Oos',
  'Losberg',
  'Louis Trichardt',
  'Lydenburg',
  'Mafeking',
  'Magaliesburg',
  'Magaliesmoot',
  'Makarios',
  'Malelane',
  'Marble Hall',
  'Messina',
  'Meyerspark',
  'Meyerton',
  'Meyerton-Suid',
  'Middelburg',
  'Middelburg-Noord',
  'Midstream',
  'Montana',
  'Montana-Oos',
  'Môrester/dosent/emeritaat',
  'Mosselbaai',
  'Naboomsprui',
  'Naboomspruit',
  'Namib-Suid',
  'Namibkus',
  'Nel',
  'Nelspruit',
  'Newcastle',
  'Niemann',
  'Nigel',
  'Noordelike Pretoria',
  'Noordrand',
  'Noordwestelike Pretoria',
  'Oberholzer',
  'Odendaalsrus',
  'Ogies',
  'Olifantsfontein',
  'Onverwacht',
  'Oos-Londen',
  'Oos-Moot',
  'Oosthuizen',
  'Otjiwarongo',
  'Ottosdal',
  'Outeniqua',
  'Outjo',
  'Panorama',
  'Parkrand',
  'Parys',
  'Phalaborwa',
  'Philadelphia',
  'Pierneef',
  'Piet Potgieter',
  'Pietermaritzburg',
  'Pieterse',
  'Pinetown',
  'Postmasburg',
  'Potchefstroom',
  'Potchefstroom-Noord',
  'Potchefstroom-Suid',
  'Potgietersrus',
  'Pretoria',
  'Pretoria-Noorderlig',
  'Pretoria-Oos',
  'Pretoria-Wes',
  'Primrose-Oos',
  'Randburg',
  'Randfontein Midpark',
  'Rensburg',
  'Rietvallei',
  'Riviere',
  'Robberts',
  'Roedtan',
  'Rooihuiskraal',
  'Rossouw-Lombard',
  'Ruskoppies',
  'Rustenburg-Kloof',
  'Rustenburg-Suid',
  'Rustenburg-Tuine',
  'Schoemansdal',
  'Secunda',
  'Selcourt',
  'Siekte Emeritaat',
  'Silverton',
  'Sinodaal',
  'Sionspoort',
  'Springs-Noord',
  'Springs-Oos',
  'Standerton',
  'Stellenbosch',
  'Stilfontein-Wes',
  'Strand',
  'Suidoos-Witbank',
  'Sundra',
  'Swartkop',
  'Swellendam',
  'Trichardtsfontein',
  'Tzaneen',
  'Vaalharts',
  'Van Der Hoff',
  'Van Warmelo',
  'Vanderkloof',
  'Ventersdorp',
  'Viljoenskroon',
  'Villieria',
  'Villiers/emeritaat',
  'Vliegepoort',
  'Volksrust',
  'Vryheid',
  'Wapadrant',
  'Warmbad',
  'Waterberg',
  'Waterval Boven',
  'Welgelegen-Pietersburg',
  'Weltevrede',
  'Weskus',
  'Wesmoot',
  'Westonaria',
  'Windhoek',
  'Witbank-Noord',
  'Witbank-Suid',
  'Witfield',
  'Witfontein',
  'Wolmaransstad',
  'Wonderboom',
  'Worcester',
  'Zesfontein',
  'Zuurfontein',
  'Zwartruggens'
] as const;

export type NHKAGemeenteNaam = typeof NHKA_GEMEENTES[number];

// Helper function to sort gemeentes with user's gemeente first
export const sortGemeentesWithUserFirst = <T extends { naam: string }>(
  gemeentes: T[],
  userGemeenteNaam?: string | null
): T[] => {
  if (!userGemeenteNaam) return gemeentes;
  
  return [...gemeentes].sort((a, b) => {
    // User's gemeente always comes first
    if (a.naam === userGemeenteNaam) return -1;
    if (b.naam === userGemeenteNaam) return 1;
    // Otherwise sort alphabetically
    return a.naam.localeCompare(b.naam);
  });
};

// Local storage key for remembering last selected gemeente
export const LAST_GEMEENTE_KEY = 'nhka_last_gemeente';

// Get last selected gemeente from localStorage
export const getLastSelectedGemeente = (): string | null => {
  try {
    return localStorage.getItem(LAST_GEMEENTE_KEY);
  } catch {
    return null;
  }
};

// Save last selected gemeente to localStorage
export const saveLastSelectedGemeente = (gemeenteNaam: string): void => {
  try {
    localStorage.setItem(LAST_GEMEENTE_KEY, gemeenteNaam);
  } catch {
    // Ignore localStorage errors
  }
};
